### ISSUE TITLE
Namespace for p5.connect

### ISSUE THREAD

**Issue by polyrhythmatic** [polyrhythmatic/p5-hardware#1]
Hey @lmccart ! As the client end of p5.connect is taking shape, @vanevery and I had a discussion about where the constructors should live for this. Pinging @tigoe on this as well.

The overall package is p5.Connect. However, currently the standard in p5 is to add functions to the global space. This sort of makes sense with serial because it follows how the namespace works with processing. However, I am hoping to expand p5 connect to support at a minimum, the following devices:

- Serial
- Midi
- HID (game controllers)
- ACN (dmx controller for lighting)
- OSC
- Leapmotion?

Adding all of these to the global namespace seems a bit insane. I would personally prefer to have them as a child of the connect object. Additionally, they would all share the same Connect object since there is one websocket server between it and the app.

I think it will make more sense to have everything as a child of the connect object. Otherwise you have to declare the connect object

`var connect = new Connect(<host>, <port>)`

and then declare your serial or midi object

`var serial = new Serial();`

with no obvious connection between the two.

I think it would be best to declare the connect object and instantiate from it

`var connect = new Connect(<host>, <port>)`
`var serial = new connect.Serial();` 

What is everyone else's thoughts on this?

p.s., everything is on the [dev branch](https://github.com/polyrhythmatic/p5-connect/tree/dev) for now

**Comment by tigoe** [comment]
Are we still assuming that everything connected through Connect is local to your computer? No network sockets? What about Bluetooth?

Reason I ask is because Connect says to me Network as well as local devices. Is that the intention?

**Comment by polyrhythmatic** [comment]
@tigoe no plans for network, this was just the name I came up with. Any suggestions? p5.hardware?

**Comment by tigoe** [comment]
If no plans for network, then p5.hardware is pretty good. Makes the distinction nicely.

**Comment by lmccart** [comment]
hi sorry for the delay on this, I think the namespacing as suggested makes sense, and @tigoe makes a good point, p5.Hardware sounds like a good name.

**Comment by polyrhythmatic** [comment]
@lmccart thanks for your input! Ok - creating a serial object will look like:

`serial = new p5.Hardware.Serial();`

My question is then: if we are going to add OSC communication does p5.Hardware still make sense?

**Comment by lmccart** [comment]
p5.Devices?

**Comment by tigoe** [comment]
Devices is nice.

Tom

**Comment by polyrhythmatic** [comment]
I appreciate the feedback but after some thinking, I'll be keeping the name as "p5.Connect" in order to support future additions to the project. 

Thanks again @lmccart for the input on hierarchy
